apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tms-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - tms.local
      secretName: tms-tls
  rules:
    - host: tms.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tms-app
                port:
                  number: 80
