apiVersion: v1
kind: Secret
metadata:
  name: tms-tls
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    replace-with-certificate
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    replace-with-private-key
    -----END PRIVATE KEY-----
